[WIP] [DA-3768] Check Intake API Payload for withdrawn PIDs
all-of-us/raw-data-repository pull request #3672
Opened 2023-10-24 14:22 UTC by shahwaiz14

## Resolves *[ticket # 3768](https://precisionmedicineinitiative.atlassian.net/jira/software/c/projects/DA/boards/11?assignee=712020%3A769e4847-aa22-4eb2-aea1-0cb378cf6a5b&selectedIssue=DA-3768)*

## Description of changes/additions
- Added cloud tasks that will send slack alert to `rdr-nph-alerts` channel.
- Added function in Participant Dao that will check and return PIDs of withdrawn participant, given a list of PIDs. 

## Tests
- [] unit tests

Unit tests will be added soon.

2023-11-01 17:47 UTC, dtharpeuno requested changes

2023-11-01 17:47 UTC, dtharpeuno commented on rdr_service/api/ancillary_study_cloud_tasks_api.py
>          return {"success": True}
So this is super specific to Participant Ids being withdrawn. Can we make this more general as it was before and either create a new cloud task endpoint just for withdrawn actions?

2023-11-01 17:47 UTC, dtharpeuno commented on rdr_service/resource/main.py
> +                      endpoint="nph_incident_task", methods=["POST"])
Same here with the comment about making this more generalized.

2023-11-01 17:47 UTC, dtharpeuno commented on tests/dao_tests/test_participant_dao.py
> +        self.assertEqual(result, expected_result)
TBH the more tests the better but moving forward I think we can not add tests for utility methods in the daos unless its super specific. Can we also edit this to lean into the provided generators?

2023-11-01 17:47 UTC, dtharpeuno commented on rdr_service/api/nph_intake_api.py
> +        pids = [ele["nph_participant_id"] for ele in self.participant_response]
:nit Can we change this to a `.get`.

2023-11-01 23:43 UTC, dtharpeuno approved these changes

2023-11-02 18:49 UTC, j-kanuch approved these changes

2023-11-03 01:24 UTC, merged