Da 4019
all-of-us/raw-data-repository pull request #3824
Opened 2024-03-07 14:43 UTC by DaveK-14

## Resolves *[DA-4019](https://precisionmedicineinitiative.atlassian.net/browse/DA-4019)*

## Description of changes/additions
Added new logic to the re-pair tool that allows to pair biobank orders and physical measurements, with optional flag for updating finalized site ids as well.

## Tests
- dao_tests/biobank_order_dao_tests.test_repairing_an_order
- dao_tests/physical_measurements_dao_tests.test_repairing_a_record

2024-03-07 17:25 UTC, ayazamlani requested changes

2024-03-07 17:25 UTC, ayazamlani commented on rdr_service/rdr_client/pairing_assigner.py
> +  pairing_assigner.py file.csv --pairing [site|organization|awardee|biospecimen|physical_measurements] \
pm & b are supposed to be optional flags, not finalization. we shouldn't be changing how we pair from site, org or awardee. Only updating the additional fields if --biospecimen flag, --physical_measurements flag, or both. 

Finalization should be updated automatically if these flags are added, no need for an optional flag for finalization.

2024-03-07 17:25 UTC, ayazamlani commented on rdr_service/rdr_client/pairing_assigner.py
> +            elif pm_sync:
please allow for all fields to be populated if both optional flags are added, not one choice or the other.

2024-03-07 17:25 UTC, ayazamlani commented on rdr_service/dao/biobank_order_dao.py
> +        elif resource["status"].lower() == "re-pairing":
this is cool. I'll need to learn more about the resource['status'] and how it works with re-pairing.

2024-03-14 05:53 UTC, ayazamlani requested changes
there are some auto reformatting happening that is getting pushed up making it difficult to decipher which code is yours. Please try to only push up your code changes so we can easily see what you changed.

2024-03-14 05:53 UTC, ayazamlani commented on rdr_service/rdr_client/pairing_assigner.py
> +        sys.exit("Pairing must be one of site|organization|awardee|biospecimen|physical_measurements")
no need for biospecimen|physical_measurements in this sys.exit()

2024-03-14 05:53 UTC, ayazamlani commented on rdr_service/rdr_client/pairing_assigner.py
> +        help="set level of pairing as one of" "[site|organization|awardee|biospecimen|physical_measurements]",
also pls remove biospecimen|physical_measurements here

2024-03-14 21:17 UTC, ayazamlani requested changes

2024-03-14 21:17 UTC, ayazamlani commented on tests/dao_tests/test_biobank_order_dao.py
> +        self.assertNotEqual(updated_order.sourceSiteId, order.sourceSiteId)
can we see the new site ID number in the test and assertEquals that the updated_order .* 
 = new_site_id

2024-03-14 21:17 UTC, ayazamlani commented on tests/dao_tests/test_physical_measurements_dao.py
> +        self.assertNotEqual(measurement.createdSiteId, updated_measurement.createdSiteId)
same here, can we pls see the new site ID and assertEquals the new_site_id

2024-03-25 15:50 UTC, dtharpeuno approved these changes

2024-03-25 15:50 UTC, dtharpeuno commented on tests/dao_tests/test_physical_measurements_dao.py
> +    def test_repairing_a_record(self):
:nit should be "an"

2024-03-25 19:08 UTC, ayazamlani approved these changes

2024-03-25 19:30 UTC, merged